linters:
  disable-all: true
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects unused assignments
    - staticcheck   # Go static analysis
    - unused        # Checks for unused constants, variables, functions and types
    - typecheck     # Like the front-end of a Go compiler
    
    # Code style linters
    - goimports     # Manage imports and format code
    - gofmt         # Format Go code
    - gofumpt       # Stricter gofmt
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter
    - misspell      # Fix spelling errors
    - whitespace    # Tool for checking trailing whitespace
    - sloglint      # Structured logging linter

    # Additional useful linters
    - gocritic      # Provides many different checks
    - godot         # Check comment ends with a period
    - unconvert     # Remove unnecessary conversions
    - unparam       # Find unused function parameters
    
    - wsl           # Whitespace Linter - Forces empty lines
    - sqlclosecheck
    - gosec
    - bodyclose

linters-settings:
  sloglint:
    no-mixed-args: true     # Don't mix key-value pairs and attributes
    static-msg: true        # Enforce using static values for log messages

  gofumpt:
    extra-rules: true
  
  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - checkPrivateReceivers
          - disableStutteringCheck

  wsl:
    allow-assign-and-anything: true
    allow-trailing-comment: true
    force-err-cuddling: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam
        - dupl
    
    - path: _test\.go
      linters:
        - godot

  max-issues-per-linter: 0
  
  max-same-issues: 0



output:
  formats:
    - format: colored-line-number
      path: stdout
  sort-results: true
  print-issued-lines: true
  print-linter-name: true

run:
  timeout: 5m

  tests: true

  concurrency: 4

  go: '1.24'